#配置springService别名
spring:
  application:
    name: eureka
#端口号
server:
  port: 8100
#配置 eureka sever
eureka:
  instance:
    hostname: localhost # ip 地址 目前是本地
  client:
    register-with-eureka: false #禁止自己当做服务注册
    fetch-registry: false       #屏蔽注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机配置